### PR TITLE
the discord don't work

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by afkvido** [comment]
thanks for telling me. dsc.bio broke. 

imma replace it with my server

**Comment by afkvido** [comment]
i mean i could close it because it has no changes

or i could give you the contributor role

**Comment by afkvido** [comment]
:)

**Comment by donaldli2020** [comment]
why did you merge empty commit lmao
i made pull request bc no issues

**Comment by afkvido** [comment]
enjoy the contributor role

**Pull request merged**
